name: 'Install CmdStan with caching'
description: 'Install CmdStan with caching'
inputs:
  cmdstan-version:
    description: 'CmdStan version to install (use "latest" for the latest version)'
    required: false
    default: 'latest'
  num-cores:
    description: 'Number of cores to use for building CmdStan'
    required: false
    default: '1'
runs:
  using: 'node12'
  main: 'index.js'
