name: Test Install CmdStan Action

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:  

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2

    - name: Install Cmdstan 2.36.0
      uses: ./install-cmdstan
      with:
        cmdstan-version: '2.36.0'
        num-cores: 1

    - name: Validate CmdStan 2.36.0 is installed correctly
      if: runner.os != 'Windows'
      run: |
        cmdstanr::check_cmdstan_toolchain()
        cmdstanr::set_cmdstan_path("~/.cmdstan/cmdstan-2.36.0")
        cmdstanr::cmdstan_path()
        cmdstanr::cmdstan_version()
        stopifnot("Version is not 2.36.0" = cmdstanr::cmdstan_version() == "2.36.0")
      shell: Rscript {0}

    - name: Check that Cmdstan 2.36.0 can be used to fit a model
      run: |
        library(cmdstanr)
        set_cmdstan_path("~/.cmdstan/cmdstan-2.36.0")
        file <- file.path(cmdstan_path(), "examples/bernoulli/bernoulli.stan")
        mod <- cmdstan_model(file, force_recompile = TRUE, quiet = FALSE)
        stan_data <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))
        fit_mcmc <- mod$sample(data = stan_data, seed = 123, chains = 2, parallel_chains = 2)
      shell: Rscript {0}
