name: Test CmdStan Installation Action

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Determine Number of Cores
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          echo $(echo %NUMBER_OF_PROCESSORS%)
        else
          echo $(nproc)
        fi

    - name: Install CmdStan (Main Branch)
      uses: epinowcast/actions/install-cmdstan@main
      with:
        cmdstan-version: 'latest'
    
    - name: Validate Installation
      run: |
        echo "CmdStan installed in: ${CMDSTAN_PATH}"
        if [ -d "${CMDSTAN_PATH}" ]; then
          echo "CmdStan directory found."
        else
          echo "CmdStan directory not found."
          exit 1
        fi
