name: Test Install CmdStan Action

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:  

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install cmdstanr
      run: |
        install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
      shell: Rscript {0}
    
    steps:
    - name: Install the latest Cmdstan
      uses: epinowcast/actions/install-cmdstan@main
      with:
        cmdstan-version: 'latest'
        num-cores: 2
      
    - name: Validate the latest CmdStan is installed correctly
      run: |
        cmdstanr::check_cmdstan_toolchain()
        cmdstanr::cmdstan_path()
        cmdstanr::cmdstan_version()
      shell: Rscript {0}

    - name: Install Cmdstan 2.33.1
      uses: epinowcast/actions/install-cmdstan@main
      with:
        cmdstan-version: '2.33.1'
        num-cores: 1

    - name: Validate CmdStan 2.33.1 is installed correctly
      run: |
        cmdstanr::check_cmdstan_toolchain()
        cmdstanr::cmdstan_path()
        cmdstanr::cmdstan_version()
        stopifnot("Version is not 2.33.1" = cmdstanr::cmdstan_version() == "2.33.1")
      shell: Rscript {0}
