name: Test Install CmdStan Action

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:  

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Determine Number of Cores (Unix)
      if: runner.os != 'Windows'
      run: |
        numCores=$(nproc)
        echo "NUM_CORES=$numCores" >> $GITHUB_ENV
      shell: bash

    - name: Determine Number of Cores (Windows)
      if: runner.os == 'Windows'
      run: |
        $numCores = [Environment]::ProcessorCount
        echo "NUM_CORES=$numCores" | Out-File -Append -FilePath $env:GITHUB_ENV
      shell: pwsh

    - name: Install CmdStan
      uses: epinowcast/actions/install-cmdstan@main
      with:
        cmdstan-version: 'latest'

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Validate Installation
      run: |
        install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
        cmdstanr::check_cmdstan_toolchain()
      shell: Rscript {0}

